### PR TITLE
Exception message when no operations defined impoved

### LINKED ISSUE #232: Unclear exception message when no operations defined
If we have a class where no methods annotated with `@Operation` we get exceptions with this message:
image

We should improve it to make it more clear.

### PR DESCRIPTION
**Pull request by avpotapov00**
Closes #232

### CODE REVIEW

File: src/jvm/test/org/jetbrains/kotlinx/lincheck_test/representation/NoOperationsDefinedTest.kt [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+/**
+ * This class is used to test the exception message when no operations are defined in a tested class.
+ */
+class NoOperationsDefinedTest {
+
+    @Test
+    fun test() {
+        val exception = assertThrows(IllegalArgumentException::class.java) { ModelCheckingOptions().check(this::class) }
+        assertEquals(
+            "At least one method in a tested class should be marked as @Operation to make random scenarios generation possible. Please see official guide for more details.",
```
Comment (ndkoval) [inline src/jvm/test/org/jetbrains/kotlinx/lincheck_test/representation/NoOperationsDefinedTest.kt:29]: Move the message to an internal constant

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/LinChecker.kt [hunk 2]
```diff
@@ -130,6 +132,12 @@ class LinChecker (private val testClass: Class<*>, options: Options<*, *>?) {
             RandomProvider::class.java
         ).newInstance(this, testStructure, randomProvider)
 
+    private fun checkAtLeastOneMethodIsMarkedAsOperation(testClass: Class<*>) {
+        require (testClass.methods.any { it.isAnnotationPresent(Operation::class.java) }) {
+            "At least one method in a tested class should be marked as @Operation to make random scenarios generation possible. Please see official guide for more details."
```
Comment (ndkoval) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/LinChecker.kt:137]: Soon, we'll provide an API that will not use annotations, and functions will be passed by reference. Please generalize the message correspondingly.

**Review by ndkoval — CHANGES_REQUESTED** [review]

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/LinChecker.kt [hunk 3]
```diff
@@ -167,4 +173,7 @@ fun <O : Options<O, *>> O.check(testClass: Class<*>) = LinChecker.check(testClas
  */
 fun <O : Options<O, *>> O.check(testClass: KClass<*>) = this.check(testClass.java)
 
-internal fun <O : Options<O, *>> O.checkImpl(testClass: Class<*>) = LinChecker(testClass, this).checkImpl()
\ No newline at end of file
+internal fun <O : Options<O, *>> O.checkImpl(testClass: Class<*>) = LinChecker(testClass, this).checkImpl()
+
+internal const val NO_METHOD_MARKED_AS_OPERATION_MESSAGE =
```
Comment (ndkoval) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/LinChecker.kt:178]: I would call it something like "NO_OPERATION_ERROR_MESSAGE", as we are going to get rid of annotations

File: src/jvm/test/org/jetbrains/kotlinx/lincheck_test/representation/NoOperationsDefinedTest.kt [hunk 4]
```diff
@@ -0,0 +1,32 @@
...
+import java.lang.IllegalArgumentException
+
+/**
+ * This class is used to test the exception message when no operations are defined in a tested class.
+ */
+class NoOperationsDefinedTest {
+
+    @Test
+    fun test() {
+        val exception = assertThrows(IllegalArgumentException::class.java) { ModelCheckingOptions().check(this::class) }
```
Comment (ndkoval) [inline src/jvm/test/org/jetbrains/kotlinx/lincheck_test/representation/NoOperationsDefinedTest.kt:28]: Why `IllegalArgumentException`?

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/LinChecker.kt [hunk 5]
```diff
@@ -197,4 +203,6 @@ fun <O : Options<O, *>> O.check(testClass: Class<*>) = LinChecker.check(testClas
  */
 fun <O : Options<O, *>> O.check(testClass: KClass<*>) = this.check(testClass.java)
 
-internal fun <O : Options<O, *>> O.checkImpl(testClass: Class<*>) = LinChecker(testClass, this).checkImpl()
\ No newline at end of file
+internal fun <O : Options<O, *>> O.checkImpl(testClass: Class<*>) = LinChecker(testClass, this).checkImpl()
+
+internal const val NO_OPERATION_ERROR_MESSAGE = "You should provide at least one operation to check. Please see the official guide: https://kotlinlang.org/docs/introduction.html"
```
Comment (ndkoval) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/LinChecker.kt:208]: You must specify at least one operation to test. Please refer to the user guide: https://kotlinlang.org/docs/introduction.html

**Review by ndkoval — CHANGES_REQUESTED** [review]

**Review by ndkoval — APPROVED** [review]
