### PR TITLE
#337 - output fixed in case of an incorrect arguments count in th cus…

### LINKED ISSUE #337: Fix the error output when wrong number of parameters passed to actor function in custom scenario DSL

### PR DESCRIPTION
**Pull request by avpotapov00**
Closes #337

### CODE REVIEW

**Comment by ndkoval** [comment]
@avpotapov00, thanks for the PR! Please make sure that the tests pass so we can review the code.

File: src/jvm/test/org/jetbrains/kotlinx/lincheck_test/representation/IncorrectArgumentsCountInCustomScenarioActorTest.kt [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+
+    @Test
+    fun testTooFew() {
+        val exception = Assert.assertThrows(IllegalArgumentException::class.java) {
+            ModelCheckingOptions()
+                .addCustomScenario {
+                    parallel { thread { actor(::operation) } }
+                }
+        }
+        assertEquals("The count of the supplied parameters for the operation method is incorrect: 1 arguments expected, 0 supplied.", exception.message)
```
Comment (ndkoval) [inline src/jvm/test/org/jetbrains/kotlinx/lincheck_test/representation/IncorrectArgumentsCountInCustomScenarioActorTest.kt:33]: Invalid number of the operation ${operation.name} parameters: 1 expected, 0 provided."

**Review by ndkoval — APPROVED** [review]
