### PR TITLE
Fix Java 11 performance bug

### LINKED ISSUE #308: Investigate performance issues due to Java agents on Java 11 builds
A new approach to byte-code transformations via Java-agent #296 introduced significant performance overhead on some Java configurations (most notably, the [Java 11 configuration](https://teamcity.jetbrains.com/buildConfiguration/KotlinTools_KotlinxLincheck_BuildDevelopOnJava11/4581382?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildChangesSection=true) on our CI builds). 

The source of this performance degradation is unclear and needs to be investigated.

### PR DESCRIPTION
**Pull request by eupp**
Closes #308

This PR fixes the performance problem accidentally introduced in #296 , that manifested on our Java 11 CI builds. 
The root cause of the problem and the solution are described below. 

The problem was related to the JVM classes re-transformation, performed by the Java agent. 
For model checking instrumentation mode, the class re-transformation was performed lazily on demand. 
However, for the stress strategy, all the loaded classes were re-transformed eagerly for each Lincheck test.
During a long JVM run (e.g. in case of our CI builds), a lot of classes can be loaded to the JVM, and for each Lincheck test run, the Lincheck JVM agent in the stress model would try to re-transform them.

However, for the stress strategy we actually only need to intercept the suspension points, that is calls to certain internal coroutine methods. The observation is that most of the loaded classes would not contain these calls, so there is no need to constantly re-transform them. 

So the solution, implemented in this PR, is to remember all the loaded classes that actually have coroutine calls inside them, and only re-transform these classes (or newly loaded classes) on subsequent Lincheck agent installations.

### CODE REVIEW

File: src/jvm/test/org/jetbrains/kotlinx/lincheck_test/verifier/linearizability/RendezvousChannelCustomTest.kt [hunk 1]
```diff
@@ -41,7 +41,7 @@ class RendezvousChannelCustomTest : VerifierState() {
     private val pollFun = RendezvousChannelCustomTest::poll
 
     @Test
-    fun testCancellation_01() = withLincheckJavaAgent(InstrumentationMode.STRESS) {
```
Comment (ndkoval) [inline src/jvm/test/org/jetbrains/kotlinx/lincheck_test/verifier/linearizability/RendezvousChannelCustomTest.kt:44]: Shouldn't the verifier track the `getResult` calls?

File: gradle.properties [hunk 2]
```diff
@@ -17,7 +17,7 @@ lastCopyrightYear=2023
 
 jdkToolchainVersion=17
 runAllTestsInSeparateJVMs=false
-instrumentAllClassesInModelCheckingMode=false
+instrumentAllClasses=false
```
Comment (ndkoval) [inline gradle.properties:20]: Note: with this change, the Teamcity build name and configuration should be adjusted accordingly.

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt [hunk 3]
```diff
@@ -155,11 +171,9 @@ internal object LincheckJavaAgent {
...
             .filter {
                 // Filter classes that were transformed by Lincheck and should be restored.
-                if (instrumentationMode == MODEL_CHECKING || !INSTRUMENT_ALL_CLASSES_IN_MODEL_CHECKING_MODE) {
-                    it.name in instrumentedClassesInTheModelCheckingMode
-                } else {
-                    true
-                }
+                if (!INSTRUMENT_ALL_CLASSES) {
+                    it.name in instrumentedClasses
+                } else true
```
Comment (ndkoval) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt:176]: Please wrap `true` with brackets:
```
if (...) {
} else {
  true 
}
```

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt [hunk 4]
```diff
@@ -312,17 +325,21 @@ internal object LincheckClassFileTransformer : ClassFileTransformer {
...
+        if (!INSTRUMENT_ALL_CLASSES &&
+            instrumentationMode == MODEL_CHECKING &&
+            className.canonicalClassName !in instrumentedClasses) {
+            return null
         }
         return transformImpl(loader, className, classBytes)
     }
 
-    private fun transformImpl(loader: ClassLoader?, className: String, classBytes: ByteArray): ByteArray = transformedClassesCache.computeIfAbsent(className) {
+    private fun transformImpl(loader: ClassLoader?, className: String, classBytes: ByteArray): ByteArray = transformedClassesCache.computeIfAbsent(className.canonicalClassName) {
```
Comment (ndkoval) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt:342]: Why `canonicalClassName`?

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt [hunk 5]
```diff
@@ -106,18 +107,33 @@ internal object LincheckJavaAgent {
...
+
+            // In the stress testing mode, Lincheck needs to track coroutine suspensions.
+            // As an optimization, we remember the set of loaded classes that actually
+            // have suspension points, so later we can re-transform only those classes.
+            instrumentationMode == STRESS -> {
+                check(instrumentedClasses.isEmpty())
+                val classes = getLoadedClassesToInstrument().filter {
+                    // new classes that were loaded after the latest STRESS mode re-transformation
+                    !transformedClassesStress.containsKey(it.name) ||
+                    // old classes that were already loaded before and have coroutine method calls inside
```
Comment (ndkoval) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt:128]: It might be the first time when a stress test is running, so `coroutineCallingClasses` is still empty. Therefore, you can ignore some classes that should not be ignored.

**Review by ndkoval — CHANGES_REQUESTED** [review]

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt (hunk 5 above)
Comment (eupp) [reply src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt:128]: Yes, in this case `transformedClassesStress` would be empty, and the check `!transformedClassesStress.containsKey(it.name)` will return true.

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt (hunk 4 above)
Comment (eupp) [reply src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt:342]: Because the other place where I use `transformedClassesStress` is inside `install` method, where I have the `Class` instance, and I can only obtain its canonical name. 

So it is easier to convert ASM's internal name to the canonical name here, than the other way around.

File: src/jvm/test/org/jetbrains/kotlinx/lincheck_test/verifier/linearizability/RendezvousChannelCustomTest.kt (hunk 1 above)
Comment (eupp) [reply src/jvm/test/org/jetbrains/kotlinx/lincheck_test/verifier/linearizability/RendezvousChannelCustomTest.kt:44]: Yes, but `withLincheckJavaAgent` is already called from the `verify` method.

Comment (ndkoval) [reply src/jvm/test/org/jetbrains/kotlinx/lincheck_test/verifier/linearizability/RendezvousChannelCustomTest.kt:44]: Is it? I don't see that. 

By the way, I also think we currently might have a bug with the model-checking mode, as the lazy transformation might not work in the verification phase, as we do not analyze anything in this phase, and, therefore, we do not ensure that the code dependencies are transformed.

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt (hunk 4 above)
Comment (ndkoval) [reply src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt:344]: Alright, I got it. Can we please use `canonicalClassName` and `internalClassName` everywhere to highlight whether the class name is canonical or internal in each case? I understand that it is not a part of this PR, but with this explicit notion, it is easier to review the PR properly.

File: src/jvm/test/org/jetbrains/kotlinx/lincheck_test/verifier/linearizability/RendezvousChannelCustomTest.kt (hunk 1 above)
Comment (eupp) [reply src/jvm/test/org/jetbrains/kotlinx/lincheck_test/verifier/linearizability/RendezvousChannelCustomTest.kt:44]: > Is it?

Yes, here I mean special `verify` method that we only use in `RendezvousChannelCustomTest` and similar tests that test the verifier algorithm. This method calls `withLincheckJavaAgent`, so everything is okay. 

> By the way, I also think we currently might have a bug with the model-checking mode, as the lazy transformation might not work in the verification phase, as we do not analyze anything in this phase, and, therefore, we do not ensure that the code dependencies are transformed.

Yes, maybe, but that is a separate issue.

Comment (ndkoval) [reply src/jvm/test/org/jetbrains/kotlinx/lincheck_test/verifier/linearizability/RendezvousChannelCustomTest.kt:44]: Could you write a test for this and check whether there is such an issue? It does not prevent the current PR from being merged, of course.

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt (hunk 4 above)
Comment (eupp) [reply src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt]: Ok, I renamed to explicit `canonicalClassName` or `internalClassName` everywhere in the `LincheckJavaAgent.kt`.

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/transformers/CoroutineSupportTransformers.kt [hunk 6]
```diff
@@ -22,22 +23,30 @@ import sun.nio.ch.lincheck.*
...
+    desc: String?
+) : AdviceAdapter(ASM_API, mv, access, methodName, desc) {
 
-    override fun visitMethodInsn(opcode: Int, owner: String, name: String, desc: String, itf: Boolean) {
-        if (isCancellableContinuationGetResultMethod(owner, name)) {
+    override fun visitMethodInsn(
+        opcodeAndSource: Int,
+        className: String?,
+        methodName: String?,
+        descriptor: String?,
```
Comment (ndkoval) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/transformers/CoroutineSupportTransformers.kt:35]: I've noticed that here "desc" was renamed to "descriptor", while on line 28 "descriptor" was renamed to "desc"

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt [hunk 7]
```diff
@@ -310,27 +329,39 @@ internal object LincheckClassFileTransformer : ClassFileTransformer {
...
     }
 
-    private fun transformImpl(loader: ClassLoader?, className: String, classBytes: ByteArray): ByteArray = transformedClassesCache.computeIfAbsent(className) {
-        nonTransformedClasses[className] = classBytes
+    private fun transformImpl(
+        loader: ClassLoader?,
+        internalClassName: String,
+        classBytes: ByteArray
+    ): ByteArray = transformedClassesCache.computeIfAbsent(internalClassName.canonicalClassName) {
+        nonTransformedClasses.putIfAbsent(internalClassName.canonicalClassName, classBytes.copyOf())
```
Comment (ndkoval) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt:357]: Should we need to call `copyOf()`? If so, please explain why in the comment.

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt [hunk 8]
```diff
@@ -278,18 +298,17 @@ internal object LincheckJavaAgent {
...
     /**
      * FOR TEST PURPOSE ONLY!
-     * To test the byte-code transformation correctness for the
-     * model-checking strategy, we can transform all classes.
+     * To test the byte-code transformation correctness, we can transform all classes.
      */
-    internal val INSTRUMENT_ALL_CLASSES_IN_MODEL_CHECKING_MODE =
-        System.getProperty("lincheck.instrumentAllClassesInModelCheckingMode")?.toBoolean() ?: false
+    internal val INSTRUMENT_ALL_CLASSES =
+        System.getProperty("lincheck.instrumentAllClasses")?.toBoolean() ?: false
```
Comment (ndkoval) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt:311]: Could you please remind me why the property was renamed?

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt [hunk 9]
```diff
@@ -82,9 +83,9 @@ internal object LincheckJavaAgent {
     private var isBootstrapJarAddedToClasspath = false
 
     /**
-     * TODO
+     * Names of the classes that were instrumented since the last agent installation.
```
Comment (ndkoval) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt:86]: Please indicate that you use `canonicalClassName` here (the same for similar usages). Please consider reflecting this in the field names.

Comment (ndkoval) [reply src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt:86]: Another option would be to have two value classes for that: `CanonicalClassName` and `InternalClassName`.

Comment (ndkoval) [reply src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt:86]: Or having one `ClassName` value class everywhere with `canonicalClassName` and `internalClassName` properties.

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckClassVisitor.kt [hunk 10]
```diff
@@ -192,4 +193,6 @@ private class WrapMethodInIgnoredSectionTransformer(
         }
         visitInsn(opcode)
     }
-}
\ No newline at end of file
+}
+
+internal val coroutineCallingClasses = HashSet<String>()
```
Comment (ndkoval) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckClassVisitor.kt:198]: What is this `String`?

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckClassVisitor.kt [hunk 11]
```diff
@@ -103,7 +104,7 @@ internal class LincheckClassVisitor(
         }
         mv = JSRInlinerAdapter(mv, access, methodName, desc, signature, exceptions)
         mv = TryCatchBlockSorter(mv, access, methodName, desc, signature, exceptions)
-        mv = CoroutineCancellabilitySupportTransformer(mv, access, methodName, desc)
+        mv = CoroutineCancellabilitySupportTransformer(mv, access, className, methodName, desc)
```
Comment (ndkoval) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckClassVisitor.kt:107]: is this `className` internal or canonical? please indicate.

**Review by ndkoval — CHANGES_REQUESTED** [review]

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt (hunk 8 above)
Comment (eupp) [reply src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt:311]: Because now stress strategy also has an optimization when it does not re-transform all the classes each time, but only:
1. subset of previously seen classes that have coroutine calls;
2. new unseen classes that were loaded into VM since the last re-transformation.

This flag now disables class re-transformation optimizations for both strategies, enforcing them to always re-transform all the loaded classes.

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/transformers/CoroutineSupportTransformers.kt (hunk 6 above)
Comment (eupp) [reply src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/transformers/CoroutineSupportTransformers.kt:35]: Fair. I renamed all the arguments of `CoroutineCancellabilitySupportTransformer::visitMethodInsn` in accordance with the naming scheme used in all the other transformers:

```
override fun visitMethodInsn(opcode: Int, owner: String, name: String, desc: String, itf: Boolean)
```

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt (hunk 7 above)
Comment (eupp) [reply src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt:357]: I removed it. 

I think I've added it during debugging, but it is actually not needed.

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckClassVisitor.kt (hunk 10 above)
Comment (eupp) [reply src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckClassVisitor.kt:198]: I added a comment explaining this variable.

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt (hunk 9 above)
Comment (eupp) [reply src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt:86]: Here I added the comment mentioning that it is canonical class name.

> Another option would be to have two value classes for that: CanonicalClassName and InternalClassName.

I really like this idea. But I would prefer to implement it in a separate PR. 
The reason is that there is several places when canonical/internal class names conversion happens, and I need to carefully review them all and enforce unified rules and invariants across all codebase. 

I would like to enforce the invariant that internal class names are only used in the `transformation` module, and they are always converted to canonical class names during byte-code transformation. Using two values classes can help to enforce this rule.

The reasons is that sometimes this conversion can also lead to performance degradation. 
Sometimes, the internal class name is passed into `ManagedStrategy` methods only to be immediately converted into canonical class name. Here is an example:
https://github.com/JetBrains/lincheck/blob/ecede824e9b3399a499c9efb5aba9d69dae91aa9/src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt#L707

Because of this, additional redundant memory allocations happen at runtime (to create new `String`). 

But, as I said, there is several places in the code when this happens. So I think addressing this problem in a separate PR would be easier.

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckClassVisitor.kt (hunk 11 above)
Comment (eupp) [reply src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckClassVisitor.kt:107]: I've added a comment to the `className` field. 
Please see the comment above about `CanonicalClassName` and `InternalClassName` value classes.

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt (hunk 9 above)
Comment (ndkoval) [reply src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt]: Thank you for the detailed explanation; let's raise an issue then.

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckClassVisitor.kt (hunk 10 above)
Comment (ndkoval) [reply src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckClassVisitor.kt:201]: I don't see the comment in the code. Could you check it on your side, please?

**Review by ndkoval — CHANGES_REQUESTED** [review]

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckClassVisitor.kt (hunk 10 above)
Comment (eupp) [reply src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckClassVisitor.kt:201]: Can you please check if you see this commit?
https://github.com/JetBrains/lincheck/pull/316/commits/ea912a746c3bc8ea9c72008e984922d0ed85dcb5

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt (hunk 9 above)
Comment (eupp) [reply src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckJavaAgent.kt]: Done: https://github.com/JetBrains/lincheck/issues/328

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckClassVisitor.kt (hunk 10 above)
Comment (ndkoval) [reply src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/LincheckClassVisitor.kt:201]: Yes, now I see that

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/transformers/MethodCallTransformer.kt [hunk 12]
```diff
@@ -11,15 +11,12 @@
 package org.jetbrains.kotlinx.lincheck.transformation.transformers
 
 import org.jetbrains.kotlinx.lincheck.transformation.*
-import org.jetbrains.kotlinx.lincheck.transformation.ManagedStrategyMethodVisitor
```
Comment (ndkoval) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/transformation/transformers/MethodCallTransformer.kt:14]: Please always use "*" in imports

**Review by ndkoval — APPROVED** [review]
