### PR TITLE
At most one validation function is allowed

### LINKED ISSUE #242: Allow at most one validation function to be declared
Having more than one validation function can make Lincheck IDEA plugin development easier as there will be no need to paint validation functions that passed successfully - if it's failed, it will be painted as a failed node; if not - it won't be painted at all.
This limitation isn't inconvenient for a user, as he can always call other validation parts extracted to a separate method from the only validation function we allow.
Since [there is no usage of multiply validation functions in the open-source projects](https://grep.app/search?q=org.jetbrains.kotlinx.lincheck.annotations), we can now introduce this limitation with an appropriate warning message in case of violation.

### PR DESCRIPTION
**Pull request by avpotapov00**
Closes #242

### CODE REVIEW

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/runner/ParallelThreadsRunner.kt [hunk 1]
```diff
@@ -79,7 +79,7 @@ internal open class ParallelThreadsRunner(
         initialPartExecution = createInitialPartExecution()
         parallelPartExecutions = createParallelPartExecutions()
         postPartExecution = createPostPartExecution()
-        validationPartExecution = createValidationPartExecution()
+        validationPartExecution = validationFunction?.let { createValidationPartExecution(it) }
```
Comment (ndkoval) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/runner/ParallelThreadsRunner.kt:82]: Please encapsulate this logic

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/runner/ParallelThreadsRunner.kt [hunk 2]
```diff
@@ -340,9 +338,9 @@ internal open class ParallelThreadsRunner(
             null
         }
 
-    private fun createValidationPartExecution(): TestThreadExecution? {
-        return TestThreadExecutionGenerator.create(this, VALIDATION_THREAD_ID, validationFunctions, emptyList(), false)
-            .also { it.initialize(validationFunctions.size, 1) }
+    private fun createValidationPartExecution(validationFunction: Actor?): TestThreadExecution? {
+        return TestThreadExecutionGenerator.create(this, VALIDATION_THREAD_ID, listOf(validationFunction), emptyList(), false)
+            .also { it.initialize(1, 1) }
```
Comment (ndkoval) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/runner/ParallelThreadsRunner.kt:343]: please add argument names

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/modelchecking/ModelCheckingStrategy.kt [hunk 3]
```diff
@@ -34,13 +34,13 @@ import kotlin.random.*
  * than the number of all possible interleavings on the current depth level.
  */
 internal class ModelCheckingStrategy(
-        testCfg: ModelCheckingCTestConfiguration,
-        testClass: Class<*>,
-        scenario: ExecutionScenario,
-        validationFunctions: List<Actor>,
```
Comment (ndkoval) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/modelchecking/ModelCheckingStrategy.kt:40]: please modify only one line

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/CTestStructure.java [hunk 4]
```diff
@@ -110,43 +94,53 @@ private static void readTestStructureFromClass(
...
                 }
             }
             if (m.isAnnotationPresent(Validate.class)) {
                 if (m.getParameterCount() != 0)
                     throw new IllegalStateException("Validation function " + m.getName() + " should not have parameters");
-                validationFunctions.add(new Actor(m, Collections.emptyList()));
+                if (testStructureBuilder.validationFunction == null) {
+                    testStructureBuilder.validationFunction = new Actor(m, Collections.emptyList());
+                } else {
+                    throw new IllegalStateException("You can't have more than one validation function.\n" +
```
Comment (ndkoval) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/CTestStructure.java:124]: Let's keep the logic that obtains all validation functions, check that the list size is <= 1, and print all the validation functions if several ones are listed.

File: src/jvm/test/org/jetbrains/kotlinx/lincheck_test/representation/ValidationFunctionTests.kt [hunk 5]
```diff
@@ -94,4 +93,31 @@ class IncorrectResultsFailureWithCorrectValidationFunctionTest {
...
+    @Validate
+    fun secondCheck() {
+    }
+
+    @Test
+    fun test() {
+        val exception = assertThrows(IllegalStateException::class.java) {
+            ModelCheckingOptions().check(this::class.java)
+        }
+        assertEquals(
```
Comment (ndkoval) [inline src/jvm/test/org/jetbrains/kotlinx/lincheck_test/representation/ValidationFunctionTests.kt:116]: Let's make a test with a full output, it is easier to read

**Review by ndkoval — CHANGES_REQUESTED** [review]

**Review by ndkoval — CHANGES_REQUESTED** [review]

**Review by ndkoval — APPROVED** [review]
