### PR TITLE
Utility function for unified object hierarchy traversing

### LINKED ISSUE #402: `UnsupportedOperationException` after adding a custom scenario
The exception occurs when a custom scenario is added: 

```
java.lang.UnsupportedOperationException: can't get field offset on a record class: private final java.lang.reflect.Parameter[] java.lang.reflect.Executable$ParameterData.parameters
	at jdk.unsupported/sun.misc.Unsafe.objectFieldOffset(Unsafe.java:655)
	at org.jetbrains.kotlinx.lincheck.ObjectTraverserKt.readField(ObjectTraverser.kt:201)
	at org.jetbrains.kotlinx.lincheck.ObjectTraverserKt.enumerateObjects(ObjectTraverser.kt:74)
	at org.jetbrains.kotlinx.lincheck.ObjectTraverserKt.enumerateObjects(ObjectTraverser.kt:105)
	at org.jetbrains.kotlinx.lincheck.ObjectTraverserKt.enumerateObjects(ObjectTraverser.kt:105)
	at org.jetbrains.kotlinx.lincheck.ObjectTraverserKt.enumerateObjects(ObjectTraverser.kt:63)
	at org.jetbrains.kotlinx.lincheck.ObjectTraverserKt.enumerateObjects(ObjectTraverser.kt:105)
	at org.jetbrains.kotlinx.lincheck.ObjectTraverserKt.enumerateObjects(ObjectTraverser.kt:63)
	at org.jetbrains.kotlinx.lincheck.ObjectTraverserKt.enumerateObjects(ObjectTraverser.kt:105)
	at org.jetbrains.kotlinx.lincheck.ObjectTraverserKt.enumerateObjects(ObjectTraverser.kt:105)
	at org.jetbrains.kotlinx.lincheck.ObjectTraverserKt.enumerateObjects(ObjectTraverser.kt:105)
	at org.jetbrains.kotlinx.lincheck.ObjectTraverserKt.enumerateObjects(ObjectTraverser.kt:105)
	at org.jetbrains.kotlinx.lincheck.ObjectTraverserKt.enumerateObjects(ObjectTraverser.kt:42)
	at org.jetbrains.kotlinx.lincheck.IdeaPluginKt.createObjectToNumberMapAsArray(IdeaPlugin.kt:147)
	at org.jetbrains.kotlinx.lincheck.IdeaPluginKt.visualize(IdeaPlugin.kt:129)
	at org.jetbrains.kotlinx.lincheck.IdeaPluginKt.beforeEvent(IdeaPlugin.kt:83)
	at org.jetbrains.kotlinx.lincheck.strategy.managed.ManagedStrategy.beforeEvent(ManagedStrategy.kt:1314)
	at sun.nio.ch.lincheck.Injections.beforeEvent(Injections.java:331)
	at com.deshyt.ChannelTestBase.send(ChannelTestBase.kt:20)
	at org.jetbrains.kotlinx.lincheck.runner.TestThreadExecution406.run(Unknown Source)
	at org.jetbrains.kotlinx.lincheck.runner.FixedActiveThreadsExecutor.testThreadRunnable$lambda$10(FixedActiveThreadsExecutor.kt:172)
	at java.base/java.lang.Thread.run(Thread.java:1583)
java.lang.UnsupportedOperationException: can't get field offset on a record class: private final boolean java.lang.reflect.Executable$ParameterData.isReal
	at jdk.unsupported/sun.misc.Unsafe.objectFieldOffset(Unsafe.java:655)
	at org.jetbrains.kotlinx.lincheck.ObjectTraverserKt.readField(ObjectTraverser.kt:208)
	at org.jetbrains.kotlinx.lincheck.ObjectTraverserKt.enumerateObjects(ObjectTraverser.kt:74)
	at org.jetbrains.kotlinx.lincheck.ObjectTraverserKt.enumerateObjects(ObjectTraverser.kt:105)
	at org.jetbrains.kotlinx.lincheck.ObjectTraverserKt.enumerateObjects(ObjectTraverser.kt:105)
	at org.jetbrains.kotlinx.lincheck.ObjectTraverserKt.enumerateObjects(ObjectTraverser.kt:63)
	at org.jetbrains.kotlinx.lincheck.ObjectTraverserKt.enumerateObjects(ObjectTraverser.kt:105)
	at org.jetbrains.kotlinx.lincheck.ObjectTraverserKt.enumerateObjects(ObjectTraverser.kt:63)
	at org.jetbrains.kotlinx.lincheck.ObjectTraverserKt.enumerateObjects(ObjectTraverser.kt:105)
	at org.jetbrains.kotlinx.lincheck.ObjectTraverserKt.enumerateObjects(ObjectTraverser.kt:105)
	at org.jetbrains.kotlinx.lincheck.ObjectTraverserKt.enumerateObjects(ObjectTraverser.kt:105)
	at org.jetbrains.kotlinx.lincheck.ObjectTraverserKt.enumerateObjects(ObjectTraverser.kt:105)
	at org.jetbrains.kotlinx.lincheck.ObjectTraverserKt.enumerateObjects(ObjectTraverser.kt:42)
	at org.jetbrains.kotlinx.lincheck.IdeaPluginKt.createObjectToNumberMapAsArray(IdeaPlugin.kt:147)
	at org.jetbrains.kotlinx.lincheck.IdeaPluginKt.visualize(IdeaPlugin.kt:129)
	at org.jetbrains.kotlinx.lincheck.IdeaPluginKt.beforeEvent(IdeaPlugin.kt:83)
	at org.jetbrains.kotlinx.lincheck.strategy.managed.ManagedStrategy.beforeEvent(ManagedStrategy.kt:1314)
	at sun.nio.ch.lincheck.Injections.beforeEvent(Injections.java:331)
	at com.deshyt.ChannelTestBase.send(ChannelTestBase.kt:20)
	at org.jetbrains.kotlinx.lincheck.runner.TestThreadExecution406.run(Unknown Source)
	at org.jetbrains.kotlinx.lincheck.runner.FixedActiveThreadsExecutor.testThreadRunnable$lambda$10(FixedActiveThreadsExecutor.kt:172)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

The code is stored [here](https://github.com/de-shyt/kotlin-channels/tree/buffered-channel-expandBuffer-UnsupportedOperationException) and can be reproduced by running [`Buffered1ChannelTest`](https://github.com/de-shyt/kotlin-channels/blob/c60ae4e86a4c611ee24d135b55e85573061181a7/src/test/kotlin/com/deshyt/ChannelsLincheckTest.kt#L24).
I am using blocking operations, and for this purpose I created a `blockingActor` method in the Lincheck library. The corresponding PR is [here](https://github.com/JetBrains/lincheck/pull/414/commits/4c546ebd01eca5b261058d632b5c80841fde09e2).

Lincheck version: 2.34
Lincheck plugin version: 0.9
Intellij IDEA version: 2024.2.2

### PR DESCRIPTION
**Pull request by dmitrii-artuhov**
- Adds a utility function for proper object graph traversing and rewrites all places where such functionality was used
- Fixes #402

### CODE REVIEW

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/ObjectTraverser.kt [hunk 1]
```diff
@@ -39,106 +36,47 @@ import kotlin.coroutines.Continuation
...
-                }
-                if (value?.javaClass?.canonicalName == "kotlinx.atomicfu.AtomicInt") {
-                    value = readField(value, value.javaClass.getDeclaredField("value"))
-                }
-                if (value?.javaClass?.canonicalName == "kotlinx.atomicfu.AtomicLong") {
-                    value = readField(value, value.javaClass.getDeclaredField("value"))
-                }
-                if (value?.javaClass?.canonicalName == "kotlinx.atomicfu.AtomicBoolean") {
-                    value = readField(value, value.javaClass.getDeclaredField("_value"))
-                }
```
Comment (eupp) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/ObjectTraverser.kt:91]: Why does this special handling of atomic types was removed?

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt [hunk 2]
```diff
@@ -230,6 +232,83 @@ internal val Class<*>.allDeclaredFieldWithSuperclasses get(): List<Field> {
...
+ * set to `false`, then array fields will be traversed instead of elements.
+ *
+ * The [callback] is called for each tuple of `(fieldOwner, field, fieldValue)` of the [obj],
+ * the return value of the callback determines, what object should be traversed further
+ * (it can be something different from `fieldValue`).
+ *
+ * Parameters of [callback]:
+ * - `fieldOwner`: either `Any` - some class instance that owns the field, or `Class<*>` is case if `field` is static.
+ * - `field`: the field that currently is traversed.
+ * - `fieldValue`: the value that was read from the field.
```
Comment (eupp) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt:248]: Please document all the arguments of the function using KDoc syntax.

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt [hunk 3]
```diff
@@ -230,6 +232,83 @@ internal val Class<*>.allDeclaredFieldWithSuperclasses get(): List<Field> {
...
+                    }
+                }
+                emptyList<Field>()
+            }
+            else if (
+                (currentObj is AtomicReferenceArray<*> || currentObj is kotlinx.atomicfu.AtomicArray<*>) &&
+                treatArrayElementsAsFields
+            ) {
+                // Do the same as before, but for atomic arrays (with non-primitive types)
+                val getElementAt = currentObj.javaClass.getMethod("get", Int::class.javaPrimitiveType)
```
Comment (eupp) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt:277]: Instead of using reflection, you can just cast to `AtomicReferenceArray<*>` or `kotlinx.atomicfu.AtomicArray<*>` type, and use the required methods directly.

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt [hunk 4]
```diff
@@ -230,6 +232,83 @@ internal val Class<*>.allDeclaredFieldWithSuperclasses get(): List<Field> {
...
+                ) as Int
+
+                for (index in 0..length - 1) {
+                    getElementAt.invoke(currentObj, index)?.let { queue.add(it) }
+                }
+                emptyList<Field>()
+            }
+            else currentObj.javaClass.allDeclaredFieldWithSuperclasses
+
+        for (f in fields) {
```
Comment (eupp) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt:290]: Let's rename `f` to `field`.

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/ObjectTraverser.kt [hunk 5]
```diff
@@ -39,106 +38,72 @@ import kotlin.coroutines.Continuation
...
+
+        try {
+            if (value == null || value is Class<*> || value is ClassLoader) return@traverseObjectHierarchy null
+            objectNumberMap[value] = getObjectNumber(value.javaClass, value)
+
+            var jumpValue: Any? = value
+
+            // we jump through most of the atomic classes
+            if (isAtomic(jumpValue)) {
+                jumpValue = jumpValue!!.javaClass.getDeclaredMethod("get").invoke(jumpValue)
```
Comment (eupp) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/ObjectTraverser.kt:70]: Why don't just put this special handling of atomic types directly into `traverseObjectHierarchy` function?

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt [hunk 6]
```diff
@@ -230,6 +232,83 @@ internal val Class<*>.allDeclaredFieldWithSuperclasses get(): List<Field> {
...
+            // We wrap an unsafe read into `runCatching` to hande `UnsupportedOperationException`,
+            // which can be thrown, for instance, when attempting to read a field of
+            // a hidden class (starting from Java 15).
+            val result = runCatching { readField(currentObj, f) }
+            if (result.isFailure) continue // do not pass fields to the user, that are non-readable by Unsafe
+
+            val fieldValue = result.getOrNull()
+            val nextObject = callback(currentObj, f, fieldValue)
```
Comment (eupp) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt:298]: Why the semantics of `callback` is to return `nextObject`, instead of just boolean `shouldTraverse` flag as before?

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt [hunk 7]
```diff
@@ -10,19 +10,21 @@
...
-import sun.nio.ch.lincheck.EventTracker
-import sun.nio.ch.lincheck.TestThread
 import org.jetbrains.kotlinx.lincheck.runner.*
 import org.jetbrains.kotlinx.lincheck.strategy.managed.*
 import org.jetbrains.kotlinx.lincheck.transformation.LincheckClassFileTransformer
 import org.jetbrains.kotlinx.lincheck.util.UnsafeHolder
+import org.jetbrains.kotlinx.lincheck.util.readField
 import org.jetbrains.kotlinx.lincheck.verifier.*
+import sun.nio.ch.lincheck.EventTracker
+import sun.nio.ch.lincheck.TestThread
```
Comment (eupp) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt:20]: Unused imports?

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt [hunk 8]
```diff
@@ -230,6 +232,83 @@ internal val Class<*>.allDeclaredFieldWithSuperclasses get(): List<Field> {
...
+ *
+ * In case [treatArrayElementsAsFields] is
+ * set to `false`, then array fields will be traversed instead of elements.
+ *
+ * The [callback] is called for each tuple of `(fieldOwner, field, fieldValue)` of the [obj],
+ * the return value of the callback determines, what object should be traversed further
+ * (it can be something different from `fieldValue`).
+ *
+ * Parameters of [callback]:
+ * - `fieldOwner`: either `Any` - some class instance that owns the field, or `Class<*>` is case if `field` is static.
```
Comment (eupp) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt:246]: Isn't there a semantics collision when some `Class<*>` instance is passed as object, and its non-static field is being inspected?

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/util/UnsafeHolder.kt [hunk 9]
```diff
@@ -34,4 +34,21 @@ internal inline fun <T> readFieldViaUnsafe(obj: Any?, field: Field, getter: Unsa
         val offset = UnsafeHolder.UNSAFE.objectFieldOffset(field)
         return UnsafeHolder.UNSAFE.getter(obj, offset)
     }
+}
+
+internal fun readField(obj: Any?, field: Field): Any? {
```
Comment (eupp) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/util/UnsafeHolder.kt:39]: Let's rename to `readFieldViaUnsafe` too (there should be no ambiguity, because the other function with the same name takes additional lambda argument).

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/FieldSearchHelper.kt [hunk 10]
```diff
@@ -52,50 +44,37 @@ internal object FieldSearchHelper {
...
-                    InstanceOwnerWithName(field.name, testObject)
-                }
-                continue
-            }
-            when (val result = findObjectField(fieldValue, value, visitedObjects)) {
-                is FieldName -> {
-                    if (fieldName != null) {
-                        return MultipleFieldsMatching
+            if (value === fieldValue && !isTraverseCompleted()) {
+                if (fieldName != null) traverseResult = MultipleFieldsMatching
```
Comment (eupp) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/FieldSearchHelper.kt:61]: Please use `when` instead of `if-else-if` chains.

Comment (eupp) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/FieldSearchHelper.kt:61]: Please put `traverseResult = MultipleFieldsMatching` into parentheses `{ traverseResult = MultipleFieldsMatching } ` for clarity.

**Review by eupp — CHANGES_REQUESTED** [review]

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt (hunk 8 above)
Comment (eupp) [reply src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt:246]: Or, event worse, when a static field of `Class<*>` object is being inspected?

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt (hunk 7 above)
Comment (dmitrii-artuhov) [reply src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt:20]: They are used in `runInIgnoredSection(...)` method

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/ObjectTraverser.kt (hunk 5 above)
Comment (dmitrii-artuhov) [reply src/jvm/main/org/jetbrains/kotlinx/lincheck/ObjectTraverser.kt:70]: I don't see why we would want that. The utility function is supposed to traverse the object graph (even if the object is an atomic class), but not to perform sophisticated logic for skipping through fields.

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt (hunk 6 above)
Comment (dmitrii-artuhov) [reply src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt:298]: In order to allow skipping through fields

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/ObjectTraverser.kt (hunk 5 above)
Comment (eupp) [reply src/jvm/main/org/jetbrains/kotlinx/lincheck/ObjectTraverser.kt:70]: Atomic objects are a bit special in this regard. 
In many aspects, `AtomicInteger` is very similar to `Integer`, it is essentially just an integer, accesses to which are atomic. Similarly, `AtomicReference` is just a reference to another object.

I don't see in what cases we might want not to skip atomic classes.
Also, probably make sense to skip boxed primitive types (e.g. `Integer`), and some other classes (at least `String`) --- basically any immutable value type.

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt (hunk 3 above)
Comment (dmitrii-artuhov) [reply src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt:277]: I made it so for atomic arrays, but for atomicfu array I keep getting errors of type `org.jetbrains.kotlinx.lincheck.UtilsKt: standalone invocation of kotlinx.atomicfu.AtomicArray::getSize that was not traced to previous field load` when I access `size` field. When I use `get(...)` method I get the same kind of error. This seems to be related to [KT-47749](https://youtrack.jetbrains.com/issue/KT-47749) which is marked as fixed. Right now I don't understand why it happens in our case

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt (hunk 8 above)
Comment (dmitrii-artuhov) [reply src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt:246]: I will change the description in javadoc, but it seems that traversing `Class<*>` is not needed in any of usage of this utility function in lincheck. In snapshot replaying I also will not need to traverse `Class<*>`, because I am starting a traverse of static variables by exact reference to their instances, and not via `Class<*>` of the declaring class.

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt (hunk 6 above)
Comment (dmitrii-artuhov) [reply src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt]: changed back to return `true`/`false`)

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/ObjectTraverser.kt (hunk 5 above)
Comment (dmitrii-artuhov) [reply src/jvm/main/org/jetbrains/kotlinx/lincheck/ObjectTraverser.kt]: Seems reasonable 👍

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt (hunk 8 above)
Comment (eupp) [reply src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt]: Let's then explicitly skip any `Class` objects in the traversal function.

**Comment by eupp** [comment]
@dmitrii-artuhov thank you for working on this!

While we are here, could you also please move `ObjectTraverserTest.kt` from `lincheck` to `lincheck_test` package (it was added to incorrect package by mistake), and extend it by adding few other test cases?

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt [hunk 11]
```diff
@@ -230,6 +243,125 @@ internal val Class<*>.allDeclaredFieldWithSuperclasses get(): List<Field> {
...
+                        },
+                        { onArrayElement(currentObj, index, it) }
+                    )
+                }
+            }
+            else -> {
+                // we jump through most of the atomic classes
+                var jumpObj: Any? = currentObj
+
+                if (isAtomic(jumpObj) && jumpObj !is AtomicReference<*> && jumpObj !is kotlinx.atomicfu.AtomicRef<*>) {
```
Comment (dmitrii-artuhov) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt:334]: - absence of `jumpObj !is AtomicReference<*>` causes [ObstructionFreedomViolationEventsCutTest](https://teamcity.jetbrains.com/buildConfiguration/KotlinTools_KotlinxLincheck_BuildAggregated/4868725?hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildDeploymentsSection=false&expandBuildChangesSection=true&expandBuildTestsSection=true&expandBuildProblemsSection=true) to fail
- `jumpObj !is kotlinx.atomicfu.AtomicRef<*>` added for symmetry

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/ObjectTraverser.kt (hunk 5 above)
Comment (dmitrii-artuhov) [reply src/jvm/main/org/jetbrains/kotlinx/lincheck/ObjectTraverser.kt]: Hm, now when I use `traverseObjectGraph` in static memory snapshot restoring, I need to track fields of `AtomicInteger`, `AtomicLong`, etc.
So, maybe jump skipping must be a local optimization for `enumerateObject` method and not a common optimization. Then, I have to return `nextObj` from the callbacks `onField` and `onArrayElement`

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt (hunk 11 above)
Comment (dmitrii-artuhov) [reply src/jvm/main/org/jetbrains/kotlinx/lincheck/Utils.kt]: Removed it after this [refactoring](https://github.com/JetBrains/lincheck/pull/420#discussion_r1826093690)

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/ObjectTraverser.kt [hunk 12]
```diff
@@ -39,107 +37,84 @@ import kotlin.coroutines.Continuation
...
-            obj.forEach { element -> element?.let { enumerateObjects(it, processedObjects, objectNumberMap) } }
+    objectNumberMap[obj] = getObjectNumber(obj.javaClass, obj)
+
+    val processObject: (Any?) -> Any? = processObject@{ value: Any? ->
+        if (value == null || value is Class<*> || value is ClassLoader) return@processObject null
+
+        // we jump through most of the atomic classes
+        var jumpObj: Any? = value
+
+        if (isAtomic(jumpObj)) {
```
Comment (dmitrii-artuhov) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/ObjectTraverser.kt:60]: TODO: replace with `isAtomicClass(...)` using string comparison with classname. Due to a possibility to extend from `AtomicReference<*>` for example. So if we have `Node : AtomicReference<*>()` we want to traverse node's fields

Comment (eupp) [reply src/jvm/main/org/jetbrains/kotlinx/lincheck/ObjectTraverser.kt:58]: TODO: also handle nested atomic references case:  `AtomicReference<AtomicReference<...>>`

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/ObjectTraverser.kt [hunk 13]
```diff
@@ -39,107 +35,86 @@ import kotlin.coroutines.Continuation
...
+        while (jumpObj?.javaClass?.name != null && isAtomicClass(jumpObj.javaClass.name)) {
+            jumpObj = jumpObj.javaClass.getMethod("get").invoke(jumpObj)
+        }
+
+        if (isAtomicFU(jumpObj)) {
+            val readNextJumpObjectByFieldName = { fieldName: String ->
+                readFieldViaUnsafe(jumpObj, jumpObj?.javaClass?.getDeclaredField(fieldName)!!)
+            }
+
+            if (jumpObj is kotlinx.atomicfu.AtomicRef<*>) {
```
Comment (eupp) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/ObjectTraverser.kt:69]: shouldn't it also be `while` loop here?

File: src/jvm/test/org/jetbrains/kotlinx/lincheck_test/ObjectTraverserTest.kt [hunk 14]
```diff
@@ -0,0 +1,108 @@
...
+            objectEnumeration.keys.containsAll(
+                listOf(
+                    myObject,
+                    // atomicfu transformers [are insane and] don't allow to compile direct reference to `myObject.array`
+                    myObject.javaClass.getDeclaredField("array").get(myObject),
+                    1, 2, 3
+                )
+            )
+        )
+    }
```
Comment (eupp) [inline src/jvm/test/org/jetbrains/kotlinx/lincheck_test/ObjectTraverserTest.kt:106]: You can add a test case here for `AtomicReference<AtomicReference<...>>` case here (and similar for AFU)

Comment (dmitrii-artuhov) [reply src/jvm/test/org/jetbrains/kotlinx/lincheck_test/ObjectTraverserTest.kt:107]: added a test with inner reference for java-atomic and atomicfu references

**Review by eupp — APPROVED** [review]

**Comment by eupp** [comment]
@ndkoval please have a look

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/ObjectTraverser.kt [hunk 15]
```diff
@@ -39,107 +35,86 @@ import kotlin.coroutines.Continuation
...
-    objectNumberMap[obj] = objectNumber
-
-    var clazz: Class<*>? = obj.javaClass
-    if (clazz!!.isArray) {
-        if (obj is Array<*>) {
-            obj.forEach { element -> element?.let { enumerateObjects(it, processedObjects, objectNumberMap) } }
+    objectNumberMap[obj] = getObjectNumber(obj.javaClass, obj)
+
+    val processObject: (Any?) -> Any? = processObject@{ value: Any? ->
+        if (value == null || value is Class<*> || value is ClassLoader) return@processObject null
```
Comment (ndkoval) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/ObjectTraverser.kt:53]: Is it possible to organize the code flow without labels? The current version is hard to read.

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/FieldSearchHelper.kt [hunk 16]
```diff
@@ -52,50 +44,47 @@ internal object FieldSearchHelper {
...
+        }
 
-            if (fieldValue === value) {
-                if (fieldName != null) return MultipleFieldsMatching
-                if (!Modifier.isFinal(field.modifiers)) return FoundInNonFinalField
+        traverseObjectGraph(
+            testObject,
+            onArrayElement = { _, _, _ -> null }, // do not traverse array elements further
+            onField = { ownerObject, field, fieldValue ->
+                if (field.type.isPrimitive || fieldValue == null) return@traverseObjectGraph null
```
Comment (ndkoval) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/FieldSearchHelper.kt:61]: Can we avoid using labels, please?

**Review by ndkoval — CHANGES_REQUESTED** [review]

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/ObjectTraverser.kt [hunk 17]
```diff
@@ -39,107 +35,81 @@ import kotlin.coroutines.Continuation
...
+                null
+            }
+        },
+        onField = { _, f, value ->
+            if (
+                Modifier.isStatic(f.modifiers) ||
+                f.isEnumConstant ||
+                f.name == "serialVersionUID"
+            ) null
+            else try {
```
Comment (ndkoval) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/ObjectTraverser.kt:105]: Please make it look like the code below, with `{ .. }` brackets. Please also check other places. 

```
if (...) {
 ...
} else {
  ...
}
```

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/FieldSearchHelper.kt [hunk 18]
```diff
@@ -52,50 +44,46 @@ internal object FieldSearchHelper {
...
-                    if (fieldName != null) {
-                        return MultipleFieldsMatching
-                    } else {
-                        fieldName = result.field
+        traverseObjectGraph(
+            testObject,
+            onArrayElement = { _, _, _ -> null }, // do not traverse array elements further
+            onField = { ownerObject, field, fieldValue ->
+                if (field.type.isPrimitive || fieldValue == null) null
+                else if (value === fieldValue && !isTraverseCompleted()) {
```
Comment (ndkoval) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/FieldSearchHelper.kt:62]: Can we avoid repeating `else if` here and make the logic flow more straightforward? Please also add comments where necessary.

**Review by ndkoval — CHANGES_REQUESTED** [review]

**Review by ndkoval — APPROVED** [review]

**Comment by ndkoval** [comment]
@dmitrii-artuhov, thanks for the refactoring! Please fix the tests, and then the PR will be ready to merge.
